[toolchain]
# cargo check --all-targets --workspace
# cargo clippy --all-targets --workspace
# ```
channel = "stable"
components = ["rustfmt", "clippy"]
profile = "default" # this will override global preferred profile if such is set
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "aarch64-linux-android",
] # host target will be added automatically
# force CI